### PR TITLE
Remove tesla-streamer

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Project was removed..

### CODE REVIEW

**Comment by mark-rushakoff** [comment]
Bummer, that was a pretty cool project. Thanks for the PR!

**Comment by ReadmeCritic** [comment]
:sweat_smile:

**Comment by ReadmeCritic** [comment]
@timdorr let us know if it comes back!

**Comment by timdorr** [comment]
Oh, I merged it into the main tesla-trip project. It lives there now and is better! :smile: 

https://github.com/timdorr/tesla-trip/blob/master/lib/tasks/tesla.rake#L12-L16
https://github.com/timdorr/tesla-trip/blob/master/lib/tesla_stream_reader.rb

**Comment by ReadmeCritic** [comment]
Nice!
#7

**Pull request merged**
